version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule: { interval: weekly }
    open-pull-requests-limit: 10
    labels: [ "dependencies", "go" ]
  - package-ecosystem: terraform
    directory: "/"
    schedule: { interval: weekly }
    open-pull-requests-limit: 10
    labels: [ "dependencies", "terraform" ]
  - package-ecosystem: github-actions
    directory: "/"
    schedule: { interval: weekly }
    labels: [ "dependencies", "ci" ]