version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 60
      statements: 40
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - wrapperFunc
        - dupImport
        - ifElseChain
        - octalLiteral
        - hugeParam
      enabled-tags:
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 10
    govet:
      settings:
        printf:
          funcs:
            - (github.com/hashicorp/terraform-plugin-log/tflog).Trace
            - (github.com/hashicorp/terraform-plugin-log/tflog).Debug
            - (github.com/hashicorp/terraform-plugin-log/tflog).Info
            - (github.com/hashicorp/terraform-plugin-log/tflog).Warn
            - (github.com/hashicorp/terraform-plugin-log/tflog).Error
    lll:
      line-length: 120
      tab-width: 1
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - funlen
          - gochecknoinits
          - goconst
          - gocyclo
          - gosec
          - mnd
        path: _test\.go
      - linters:
          - lll
        source: '^//go:generate '
      - linters:
          - govet
        text: 'shadow: declaration of "err"'
      - linters:
          - gosec
        text: 'G204:'
      - linters:
          - mnd
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/pexip/terraform-provider-pexip
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
