/*
 * SPDX-FileCopyrightText: 2025 Pexip AS
 *
 * SPDX-License-Identifier: Apache-2.0
 */

resource "pexip_infinity_certificate_signing_request" "certificate_signing_request-test" {
  subject_name                 = "test.example.com"
  dn                           = "test-value"
  additional_subject_alt_names = "*.test.example.com"
  private_key_type             = "RSA2048"
  // private_key will be generated by the API if not provided
  private_key_passphrase = "test-value"
  ad_compatible          = true
  // tls_certificate is optional and omitted from test
}