/*
 * SPDX-FileCopyrightText: 2025 Pexip AS
 *
 * SPDX-License-Identifier: Apache-2.0
 */

resource "pexip_infinity_certificate_signing_request" "certificate_signing_request-test" {
  subject_name                 = "updated.example.com" // Updated value
  dn                           = "updated-value"       // Updated value
  additional_subject_alt_names = "*.updated.example.com"
  private_key_type             = "ECDSAP256" // Updated value
  // private_key will be generated by the API if not provided
  private_key_passphrase = "updated-value" // Updated value
  ad_compatible          = false           // Updated to false
  // tls_certificate is optional and omitted from test
}